### PR TITLE
Allows external events access to http error codes

### PR DESCRIPTION
**Pull request by DrummerSi**
E.G.
```javascript
app.on("endNavigate", function (e) {
	if (e.error) {
		if (e.error.invalidStatus) {
			switch (e.error.statusCode) {
				case 401: //Needs authorisation - Redirect to login page?
					console.log("AUTH REQUIRED")
					break;
				case 404: //Page not found
					console.log("NOT FOUND")
					break;
				case 500: //Error on page
					console.log("SERVER ERROR")
					break;
			}
		}
	}
});
```

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @DrummerSi,

Thanks for the PR. It makes sense. I'll take a look and merge it as soon as I can.

**Comment by eduardolundgren** [comment]
Could you add a test case for the feature, e.g. https://github.com/liferay/senna.js/blob/9c6655e0870d712b2340a0d623f6926c1fb19238/test/screen/RequestScreen.js#L171.

**Comment by eduardolundgren** [comment]
LGTM. Thanks!

**Comment by eduardolundgren** [comment]
Released https://github.com/liferay/senna.js/releases/tag/v2.0.5.

**Pull request merged**
