### PR TITLE
Removing default JS screen caching for RequestScreen.

### PR DESCRIPTION
**Pull request by henvic**

### CODE REVIEW

**Comment by henvic** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lpgray** [comment]
I also need this function.

**Comment by henvic** [comment]
Ping.

**Comment by eduardolundgren** [comment]
Relying on the browser cache is safer, indeed. Although cached screens brings huge performance benefits, specially on slow networks. The hard question here is to know when to invalidade the screens cache. Definitely, there is room to think about an automatic cache invalidation, WDYT?

For now, the `app.clearScreensCache` method is already merged to facilitate cleaning the cache pragmatically.

**Pull request closed without merging**
