### PR TITLE
emit fragmentNavigate event

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Is this something that can be added to the `event` payload of the `startNavigate` and `endNavigate` instead of introducing a new event?

Also, could you give one example where you needed that? 

Thanks.

**Comment by zenorocha** [comment]
I think this is related to #140

**Comment by mjbradford89** [comment]
Yeah this one is for #140.

We could add a flag to the start/endNavigate events designating it as a fragment navigation rather then emitting an entirely different event, but then there wouldn't be any event fired when navigating to a fragment on the same page.  Which is what Ray was originally asking for in the issue I think.

**Comment by mjbradford89** [comment]
Closing this one for now.  I'm going to reach out to Ray to clarify some things and see if there may be a better fix for this one.  Thanks!

**Comment by eduardolundgren** [comment]
Thanks.

**Pull request closed without merging**
