### PR TITLE
Avoids breaking change on the error handling contract

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @jbalsas and @vbence86 

I found an issue running the tests on https://github.com/liferay/senna.js/pull/225. One test was breaking due to the fact that it was expecting `requestError` to be thrown and it wasn't anymore. I thought it could cause regressions on people's existing code and it could be considered a breaking change. So, my idea was to not just flag the error as `requestPrematureTermination` but flag it with both `requestPrematureTermination` and `requestError`. That way existing code will still work and we also now have the new information that can help us treat the navigation error better in the app level. What do you think?

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brunobasto, I'm not seeing any errors in #225. The build for it is certainly green in all browsers: https://travis-ci.org/liferay/senna.js/builds/258554607

In any case I don't see why we shouldn't do this, so if @vbence86 agrees as well, we can merge and release.

**Comment by vbence86** [comment]
Yeah it seems a a green build, I agree with proceeding with the merge. With the ability to bubble up CORS errors to the App, it is now entirely up to the senna-liferay-portal integration how the redirect issue is handled.

**Comment by brunobasto** [comment]
Hey Chema, the reason the build was passing was because that pull request didn't have the updated metal-ajax

**Comment by jbalsas** [comment]
Oh, I see... I did test with it, though, so I'm not sure why I didn't see it, but makes sense.

I released it and we've sent https://github.com/brunobasto/liferay-portal/pull/861 with the complete fix for Liferay Portal ;)

**Pull request merged**
