### PR TITLE
Build

### PR DESCRIPTION
**Pull request by brunobasto**
@eduardolundgren 

This fixes weird caching behaviors in IE/Edge. Would be good to have a new version of senna.js including this fix before we release Liferay portal next week.

I'm not sure I built it correctly, if not, just ignore the "Build" commit.

Thx,

### CODE REVIEW

**Comment by brunobasto** [comment]
Looks like tests are having problems connecting to saucelabs..

**Comment by kenjiheigel** [comment]
@brunobasto, this might fix the sauce issue:
 https://github.com/karma-runner/karma-sauce-launcher/issues/61

**Comment by brunobasto** [comment]
Thanks, @kenjiheigel!

@mairatma should we add this to the saucelabs task on gulp-metal?

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Did we test setting `Cache-Control: no-cache` instead?

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/senna.js/compare/83cfa48~3...83cfa48) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
I merged it changing for Cache-Control header, could you test and if works I can tag it. Thanks!

**Comment by mjbradford89** [comment]
Hey @eduardolundgren, I tested it out but it doesn't seem to solve the issue.  The Cache-Control header _does_ work to prevent caching on a normal navigate, but not when being redirected.

It seems the `Cache-Control` header doesn't get carried over to the second transparent request that the browser makes (that we can't modify).  But the `If-None-Match` header does for some reason, and is enough to prevent it from serving from cache.  I'm not sure why Edge behaves this way though :sob:

**Comment by eduardolundgren** [comment]
SGTM. Just pushed another try. Could you test? Thanks!

**Comment by mjbradford89** [comment]
looks like it's fixed :joy:  Thanks @eduardolundgren @brunobasto!

**Comment by brunobasto** [comment]
Thanks, @mjbradford89!

**Pull request merged**
