### PR TITLE
Update for #148

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Eduardo,

Attached is an update for https://github.com/liferay/senna.js/issues/148.

I created a test for the multiple load events in IE11.  (btw, microsoft confirmed the bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7940171/).

For the test, I had to use an external stylesheet.  I tried to use one I created in `/test`, but because of the way gulp-metal works I couldn't find a way for it to be served up when running gulp test.  As far as I can tell this is not configurable and would require changes in what we pass to karma in gulp-metal.

So I used the bootstrap CDN, which I really didn't want to do but couldn't find a way around it.

Now as for improving the [test](https://github.com/liferay/senna.js/blob/master/test/screen/HtmlScreen.js#L255) for the original [bug](https://github.com/liferay/senna.js/issues/124), I ran into other issues.  It seems that bug extends so far as using `getComputedStyle`, like you mentioned, will actually return the correct style, even though it is not displayed as such in the browser.

This got really complicated so please grab me if it doesn't make sense :sweat_smile:.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Hey @eduardolundgren,  I updated this with your suggestions.  I also had to update the previous test now that the mutation is called from the `load()` method.

Please let me know if there are any other issues.

Thanks!

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/senna.js/compare/1672030~1...1672030) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
