### PR TITLE
Trying to reduce tests "flakyness" by making more use promises and less callbacks and moving suspicious tests to the end of the queue so that they have less chance of affecting others

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by jbalsas** [comment]
😱 It's greeen!!! 👏

**Comment by diegonvs** [comment]
OMFG

**Comment by brunobasto** [comment]
Testing a couple more times to make sure it's stable :)

**Comment by jbalsas** [comment]
😭 

```
Chrome 68.0.3440 (Windows 7 0.0.0) App should update the document.referrer upon navigation FAILED
	Error: Uncaught AssertionError: expected '/path1' to equal '/path2' (node_modules/metal/src/async/async.js:26)
```

**Comment by brunobasto** [comment]
:/

**Comment by brunobasto** [comment]
And now it passed again..

**Comment by jbalsas** [comment]
I'm retesting a couple of times more to see what's the error rate:

Attempt | Result
--- | ---
1 | ✅ 
2 | 🅾️ 
3 | ✅ 
4 | ✅ 
5 |
6 |
7 | 
8 |
9 |
10 |

**Comment by diegonvs** [comment]
Continues at #270

**Pull request closed without merging**
