### PR TITLE
Fixes some bugs by normalizing paths

### PR DESCRIPTION
**Pull request by mairatma**
Some bugs were happening due to urls ending with `/`. I've fixed two cases of this by normalizing the url.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brunobasto, do you think we still need this?

**Comment by jbalsas** [comment]
I'm closing since we haven't had a report and issues like this have already been fixed, but we'll reopen it if needed.

**Comment by jbalsas** [comment]
Actually, I just added the tests and they're failing, so I'll probably merge this :)

**Comment by brunobasto** [comment]
Hey @jbalsas, we probably still need this. I tried quickly rebasing it, but it was failing some tests. It needs more close attention.

**Comment by jbalsas** [comment]
Yeah, I'm taking a look. I'll update it as soon as I can

**Comment by eduardolundgren** [comment]
I think we do need this normalization, just make sure the code is still valid or if there is a better way to handle this in the current code base.

**Comment by zenorocha** [comment]
Yeah, this is still needed. I had to do a workaround on my personal project to fix that: https://github.com/zenorocha/zenorocha.com/blob/master/src/assets/js/main.js#L1-L4

**Comment by fernandosouza** [comment]
Resent https://github.com/liferay/senna.js/pull/215

**Pull request closed without merging**
