### PR TITLE
Make screen object available to surfaces when transitioning.

### PR DESCRIPTION
**Pull request by lucasconstantino**
In a project of mine, I had the need to attach some meta information to the screen object, which I would then use while transitioning surfaces. This pull-request is what made this possible.

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Looks good. I am currently working on v1.0.0 and this may fits better there. When branch is pushed this needs to be re-sent to there instead. Will keep this open open for reference. Thank you.

**Comment by eduardolundgren** [comment]
Could you try that in master now? If works well you can re-submit. Thanks!

**Comment by eduardolundgren** [comment]
@lucasconstantino Just wondering if you still need this feature. 1.0.0 is almost ready and would be nice to find a solution for your need. Let me know.

**Comment by lucasconstantino** [comment]
Hi there. I'm sorry, I totally forgot to have a look at this issue again. I'm certainly gonna need this feature, but I guess you can ship 1.0.0 without it if I take too long to re-submit. I'll try and have a look at that on sunday, though, if you can wait until then.

**Comment by zenorocha** [comment]
@lucasconstantino I'll close this one for now, but feel free to resend this PR if you're still facing this issue. And thanks for using Senna 🎉

**Pull request closed without merging**
