### PR TITLE
Anchor link offset are not calculated correctly

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
hey @dacousalr, can you provide a test case or describe the issue?

Thx

**Comment by dacousalr** [comment]
Hi @brunobasto,

Firstly, thanks for taking a look at this.

Most of the information I can offer you about its reproducibility is in https://github.com/liferay/senna.js/issues/221#issue-241241384.

Please, let me know if you need more information and I will try to provide it.

Best,
D.

**Comment by brunobasto** [comment]
Hey @dacousalr, sorry, my bad. I missed the link to that issue. Will take a look and let you know how it goes. Thank you!

**Comment by brunobasto** [comment]
I was able to reproduce and verified that the proposed solution fixes the issue. Once I get a green light from the tests I'll publish a version. Thanks again

**Comment by eduardolundgren** [comment]
@brunobasto Can't we use metal-position here?

**Comment by brunobasto** [comment]
Hey @eduardolundgren, I'll give it a try. The implementation looks different though, cause what it does is return the node.offsetTop + transform translation.

**Comment by eduardolundgren** [comment]
Which  one returns the transform? The pull or metal's?

**Comment by brunobasto** [comment]
metal's: https://github.com/metal/metal-position/blob/master/src/Position.js#L96

Interestingly enough, it worked. Let me run some more tests here, and if it works we can probably use it.

**Comment by eduardolundgren** [comment]
It should work. Thx.

**Comment by eduardolundgren** [comment]
Although I am wondering it it will add too much code for this. Maybe is better to keep a simpler implementation here? Or optimize the bundle.

**Comment by brunobasto** [comment]
I actually tested it a bit more, and it looks like it's not working as previously.

metal-position: https://drive.google.com/open?id=0B-Sc8uDOPJSueUpRcDZVc3o3NWs

previous solution: https://drive.google.com/open?id=0B-Sc8uDOPJSuZlFoQkxKUnNjSjQ

**Comment by brunobasto** [comment]
For testing I'm trying to mess with absolute positioning:

```
<div style="position: absolute; top: 1400px">
		<h1 style="top: 250px; position: relative;" id="section2">Section 2</h1>
```

**Comment by eduardolundgren** [comment]
Thx for testing

**Comment by brunobasto** [comment]
So, for now we could keep the proposed solution and try to figure out if metal-position currently has an issue with the calculation of the offsets, right?

**Comment by eduardolundgren** [comment]
@brunobasto yep, we can analyze metal position separate.

**Comment by dacousalr** [comment]
Thank you so much for your review and analysis, @brunobasto, @eduardolundgren

**Comment by eduardolundgren** [comment]
Np. Thanks for working on it.

**Pull request merged**
