### PR TITLE
Senna not working on HTTPS pages #152

### PR DESCRIPTION
**Pull request by mjbradford89**
Attached is an update for #152.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/liferay/senna.js/compare/87d0e80~2...87d0e80) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
thanks @eduardolundgren,  Sorry about the whitespace on the last couple pulls, I'm not sure how that's getting in there

**Comment by eduardolundgren** [comment]
It's fine. Make sure to run `gulp format lint` before pull requests and it will catch those.

**Pull request merged**
