### PR TITLE
Current senna version function

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
#232 ! @brunobasto

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
I think this has been merged and released as `2.5.0`! 🎉

**Comment by caneta** [comment]
How to get this info in Liferay 7.1 CE? `Liferay.SPA.version` or `Liferay.SPA.app.version` do not exist...
Maybe Liferay 7.1 has a Senna version < 2.5.0?

**Comment by jbalsas** [comment]
Hey @caneta, `Liferay 7.1` uses senna `2.6.2`. I was looking into this, and we only added version info here, but we don't expose it. I've created https://issues.liferay.com/browse/LPS-86070 to make sure we finish this properly.

I tried myself, and I got the following:

```
Liferay.SPA.version
08:25:14.833 "<%= version %>"
```

@diegonvs, I think the build process isn't working as expected? Could you take a look and send a followup PR?

**Pull request closed without merging**
