### PR TITLE
SF

### PR DESCRIPTION
**Pull request by brunobasto**
@eduardolundgren

### CODE REVIEW

**Comment by eduardolundgren** [comment]
There is a test failing right now:

```
Chrome 50.0.2661 (Mac OS X 10.11.4) RequestScreen should fail for invalid status code response FAILED
	Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

We suspect that this may be a bug in one of the dependencies, and not related to this fix. As soon as we address it will go back to review this pull.

Thanks!

**Comment by mjbradford89** [comment]
Hey @eduardolundgren, is that test still failing?  I can't reproduce it locally and it looks like the CI tests aren't running at all

**Comment by eduardolundgren** [comment]
It's still failing https://travis-ci.org/liferay/senna.js/builds/135607113

**Comment by mjbradford89** [comment]
ah thanks for checking! I must be looking at those logs wrong, the only messages I see are `Sauce Labs Authentication Error.` :worried:

**Comment by eduardolundgren** [comment]
@mjbradford89 Could you test on your computer on some browsers that are available to you to make sure it's passing? This change is a bit delicate and we need to be careful to avoid any regression here. Thanks!

**Comment by mjbradford89** [comment]
Hey @eduardolundgren, sure thing.  Tests all passed on the following browsers for me:
```
Chrome Mobile 51.0.2704 (Android 6.0.1): Executed 211 of 211 SUCCESS (4.659 secs / 2.64 secs)
Firefox 46.0.0 (Ubuntu 0.0.0): Executed 211 of 211 SUCCESS (5.293 secs / 3.019 secs)
Chrome 50.0.2661 (Linux 0.0.0): Executed 211 of 211 SUCCESS (5.852 secs / 3.717 secs)
Edge 13.10586.0 (Windows 10 0.0.0): Executed 211 of 211 SUCCESS (9.656 secs / 6.424 secs)
IE 11.0.0 (Windows 10 0.0.0): Executed 211 of 211 SUCCESS (12.139 secs / 7.159 secs)
```
I also tested manually and everything seems good :+1:

**Comment by eduardolundgren** [comment]
Thanks!

**Comment by eduardolundgren** [comment]
Tests are failing on CI https://travis-ci.org/liferay/senna.js/builds/142924840.

Could you analyze it and submit a fix? I've already released a version `1.5.2` with this test case failing. As soon as we fix this I release a new one.

**Comment by mjbradford89** [comment]
Sure, sorry about that.  Strange, it looks like a test is failing even on the same browsers that passed locally for me

**Comment by eduardolundgren** [comment]
No worries, it's failing on Firefox on Linux, not easy to catch without SauceLabs.

**Comment by eduardolundgren** [comment]
Actually, after re-run the test its failing on Safari 8.0.8 (Mac OS X 10.10.5). It's flaky I guess.

**Comment by eduardolundgren** [comment]
Let me know if you want me to re-run it one more time.

**Comment by eduardolundgren** [comment]
It's still failing. Correct?

**Pull request merged**
