### PR TITLE
New surface type: DelayedAsyncTransitionSurface 

### PR DESCRIPTION
**Pull request by lneves12**
This new surface will delay the screen transition until the method finishTransition is called().

This can be useful to delay the screen transition for screens using client-side rendering (angular,react), thus having a smoother page transition. **Example:** https://github.com/uyuni-project/uyuni/pull/1312

### CODE REVIEW

**Comment by lneves12** [comment]
Hey @diegonvs!

What are your thoughts on this solution?

**Comment by ncounter** [comment]
Any news/plan about this PR?

**Comment by ncounter** [comment]
Is this PR still in the queue to be evaluated and merged, or?

**Comment by wincent** [comment]
I would imagine that no, it's not going to me merged in its current form due to the merge conflicts and risk involved.

From the README:

> :warning: In the future, [the `senna` npm package](https://npmjs.com/package/senna) will be deprecated and this repo archived (ie. switched to read-only mode). Development continues in [the `liferay/liferay-portal` repo](https://github.com/liferay/liferay-portal) (more specifically, inside [the `frontend-js-spa-web` module](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-js/frontend-js-spa-web)), but not as an independent project, in order to better integrate with and serve the needs of Liferay DXP. At the time of writing, the last official release was [v2.7.9](https://github.com/liferay/senna.js/tree/v2.7.9), from the `2.x` series on the `master` branch, and it is still used by a number of pre-EOL versions of Liferay DXP, such as [7.0.x](https://github.com/liferay/liferay-portal/blob/6b14c8e0496926309a5fac347cb2d342d7412c1f/modules/apps/foundation/frontend-js/frontend-js-spa-web/package.json#L6), [7.1.x](https://github.com/liferay/liferay-portal/blob/d9a4b24bf1871d509c2bb12e38669bb8552db1a5/modules/apps/frontend-js/frontend-js-spa-web/package.json#L17), [7.2.x](https://github.com/liferay/liferay-portal/blob/ded0e9390637985231e962e4ad4cfa4639eabb26/modules/apps/frontend-js/frontend-js-spa-web/package.json#L6), and [7.3.x](https://github.com/liferay/liferay-portal/blob/c940e8fd455d59fe05fd2038410070412411947c/modules/apps/frontend-js/frontend-js-spa-web/package.json#L6).

We're currently planning on moving this into our [`liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can cut maintenance releases if needed (see [draft PR](https://github.com/liferay/liferay-frontend-projects/pull/379)) in a way that is consistent with our other projects, but we're going to have a strong preference for keeping changes that go in there minimal and conservative. At the very least, a PR like this would have to be rebased and resent there in order to be considered, so I'm going to close this one for now.

**Pull request closed without merging**
