### PR TITLE
[TS] LPS-84041

### PR DESCRIPTION
**Pull request by yuhai**
Hi Team,

**The issue only can be reproduced on IE browser (test it on IE11)**. For other browsers (chrome, firefox), the issue can't be reproduced. 

Please refer to the explanation from https://issues.liferay.com/browse/LPS-84041?focusedCommentId=1551696&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1551696

cc @dsanz, @gregory-bretall, @antonio-ortega

Regards,
Hai

### CODE REVIEW

**Comment by dsanz** [comment]
Hi @jbalsas ,

it seems that [this was fixed in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=616760) some time ago. [Fix](https://codereview.chromium.org/2356373002/patch/90001/100003) seems straightforward 

I've found that this was added to [chrome 55](https://chromereleases.googleblog.com/2016/12/chrome-for-android-update.html), see [5th commit in logs](https://chromium.googlesource.com/chromium/src/+log/55.0.2883.84/third_party/WebKit/Source/core/dom/Range.cpp). 

Our CI is running [Chrome 37, announced in 2014](https://chromereleases.googleblog.com/2014/09/chrome-for-android-update.html)

Considering our [support policy for mobile browsers](https://web.liferay.com/documents/14/21598941/Liferay+DXP+Compatibility+Matrix.pdf/0d76e070-691d-462f-9210-21e1dd700c68), which allows access to information using the latest chrome mobile available, the action item that sounds more natural to me is to update CI tests to use a more modern mobile browser.

I can't see any other alternative, as current fix is checking for IE all times (I'd say it'd be better to avoid the check). Btw, why `UA.isIe` returns true for chrome mobile?

Would this change in CI make sense Chema?

cc/ @yuhai @gregory-bretall @antonio-ortega

**Comment by jbalsas** [comment]
Hey @dsanz, the fact that we are wrapping code in a condition that is running when we don't expect it worries me. We don't know where else could this be happening, so I'd like to address that first.

@diegonvs, could you take a look to see what might be happening there with `metal-useragent`?

**Comment by dsanz** [comment]
I agree @jbalsas, that must be addressed first, regardless of the final fix we decide.
Best

**Comment by diegonvs** [comment]
Hey guys, I'll take a look on `isIE` function in `metal-useragent` :)

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diegonvs** [comment]
There isn't an error with `metal-useragent`, the problem is simulating IE user agent on chrome and execute

**Comment by diegonvs** [comment]
Hey guys, I have fixed some tests and made some changes. Could you guys see at #278? :)

**Pull request closed without merging**
