### PR TITLE
Fixes #295 - do not append query to IE link

### LINKED ISSUE #295: Query appending to IE11 link
### Expected behaviour

No query is appened to IE11 link when switching pages with different favicons.

### Actual behaviour

A query is being appended to IE11 links when switching pages with different favicons.

### Steps to reproduce

1. Start Liferay and open in IE11
2. Create a theme with a new favicon.ico file in src/images. Deploy the theme and apply it to a public page. They have been provided below.
3. Go to the public page with the new theme.
 
Themes can be found here: https://issues.liferay.com/browse/LPS-88702.
This behavior is required for https://github.com/matuzalemsteles/liferay-portal/pull/6#issuecomment-457737859. These changes will allow the different favicon to appear correctly in IE11.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @jbalsas and @brunobasto can you take a look at this? plz

**Comment by brunobasto** [comment]
code LGTM

**Comment by jbalsas** [comment]
Merged! @matuzalemsteles, could you prepare a new release so we can integrate it in portal?

Thanks!

**Comment by matuzalemsteles** [comment]
Thanks @jbalsas, I do not have permission in this repository to be able to publish, as soon as it is released we will send along with https://github.com/matuzalemsteles/liferay-portal/pull/6.

**Comment by jbalsas** [comment]
Thanks Matu! I'll get you permissions in this repo for the next time. I'll talk to @brunobasto to publish this today!

**Comment by alfonsocrisci** [comment]
thanks @jbalsas @brunobasto  ;)

**Pull request merged**
