### PR TITLE
Scheduled Navigations logic during multiple path navigation

### LINKED ISSUE #262: Cancel navigation duplicates surfaces
### Expected behaviour

Surfaces are not duplicated if I cancelled navigation.

### Actual behaviour

Surfaces are duplicated when cancelling navigation leading to problems like duplicated id, etc.

### Steps to reproduce

1. Create an app with two pages (PageA and PageB) in a such a way that you navigate between them using senna.js
2. Being on PageA, click on link to navigate to PageB.
3. Quickly, before PageB is loaded, click again to navigate to PageA.
4. Inspect the DOM and you'll see surfaces duplicated.

### Browsers affected

It's easier to reproduce on IE11 because is slower, but you can use CPU throttling in Chrome.

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @diegonvs, @brunobasto, the `document.referrer` test seems to be failing consistently. I haven't been able to see a green CI run in this PR even though I've attempted at least 6-7 retries :(

**Comment by jbalsas** [comment]
It passed!! 😱

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
@brunobasto, are you looking into this? Do you think it's safe to merge?

**Comment by jbalsas** [comment]
Thanks for checking @brunobasto! Since this will affect analytics, I don't want to push this without you being 100% sure it's fine to proceed.

**Comment by jbalsas** [comment]
Closing here, see https://github.com/liferay/senna.js/pull/267

**Pull request closed without merging**
