### PR TITLE
Changes globals build to use Rollup

### PR DESCRIPTION
**Pull request by brunobasto**
Original PR: https://github.com/liferay/senna.js/issues/172

This time I was able to see a **decrease** of 12K. Probably things are improving in Rollup. One minor issue is that I'm getting a `MIXED_EXPORTS` warning when building. It seems to complain because of these lines: https://github.com/liferay/senna.js/blob/master/src/senna.js#L11. Apparently it doesn't like that we are exporting both named and default.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Since we are doing named exports intentionally, it's probably safe just to declare that in the rollup config.

```
	dest: 'build/globals',
	src: 'src/senna.js',
	rollupConfig: {
		exports: 'named'
	}
```

**Comment by brunobasto** [comment]
@Robert-Frampton Thanks. It did remove the warning. The only thing that confused me was that we are exporting both named and default.

https://github.com/rollup/rollup/wiki/JavaScript-API#exports

> named – suitable if you're exporting more than one thing

I guess what we are doing falls into this category

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Merged, thanks!! 🎉

**Pull request closed without merging**
