### PR TITLE
fix safari and chrome mobile test failures

### PR DESCRIPTION
**Pull request by mjbradford89**
Hopefully this will fix the test issues.  I borrowed devices to test Safari and Chrome Mobile, and they are passing locally for me.

### CODE REVIEW

**Comment by mjbradford89** [comment]
:cry: still failing in Safari 8.0.8, but passing for me locally in Safari 9.1.1.  Strangely the test that is failing isn't even related to the original pull...

**Comment by eduardolundgren** [comment]
We may need to revert it until we figure it out. Let me know.

**Comment by mjbradford89** [comment]
hmm yeah maybe we should.  It's hard to test out what the problem actually is though without saucelabs, especially because there isn't a way for me to test locally in safari 8.0.8.  And most people here are on Safari 9.1.1 or higher

**Comment by brunobasto** [comment]
Hey @mjbradford89, maybe it could be tested on a VM where you can download the exact version of Safari you need. Not sure where to find it, though.

**Comment by eduardolundgren** [comment]
We can push a branch to upstream, that way we can run SauceLabs. Could you try to push a branch?

**Comment by mjbradford89** [comment]
oh cool. just pushed up https://github.com/liferay/senna.js/tree/test-failures

**Pull request merged**
