### PR TITLE
Create tracked resources example

### PR DESCRIPTION
**Pull request by mjbradford89**
These changes create a simple example for tacking stylesheets using data-senna-track.

I reused some styles from the email example.

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Looks awesome :) Thanks.

**Comment by zenorocha** [comment]
Could you mentioned AMD support on `Step 1`?

**Comment by brunobasto** [comment]
👍

**Pull request merged**
