### PR TITLE
Make sure that the second back will be trigger before the navigation

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
This fix seems flaky due to usage of setTimeout with random interval. Also it's uncertain that this is a bug because there is no test case in the pull request. Is there any other way to have it fixed? If so make sure to send with a test case. Thank you.

**Comment by brunobasto** [comment]
Hey Eduardo, this was broken in Safari 5 due to the fact that it de bounces calls to

**Comment by brunobasto** [comment]
.. history.go()

**Comment by fernandosouza** [comment]
Hey, @eduardolundgren. This pull request is only an update to a test case. Some browsers implement a debounce to navigations. CI caught it on Chrome Mobile 30.0.0 (Android 4.4.2) and I caught it on Safari 10.1 in my machine.

The use of setTimeout is needed here to skip this browser feature and make sure that the test simulates a double back before the request ending.

**Comment by brunobasto** [comment]
Yeah. The timeout is not entirely random. What we are trying to achieve is call a navigation while another is still going on. Which the test makes sure by having the load timeout be greater than the timeout to call the second history.go

**Comment by eduardolundgren** [comment]
Okay. I am merging it then. Thanks.

**Pull request merged**
